---
version: '3'

vars:
  SOURCE_FOLDER: src
  CURDIR:
    sh: pwd

tasks:
  default:
    cmds:
      - task: test
      - task: build

  mok:
    desc: run mock test api
    cmds:
      - cmd: mokapi --providers-file-directory {{.CURDIR}}/testdata/api

  mod:
    desc: update go modules, add submodules to go root
    cmds:
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_add_sub_packages.sh | bash

  build:
    desc: build binary using remote ghwfe script, requires curl
    cmds:
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_build.sh | bash

  test:
    desc: run go tests
    cmds:
      - cmd: go test ./... -v -coverpkg=./... -race -bench=.

  deploy:
    desc: build and copy to my personal arch mybins folder
    cmds:
      - task: build
      - cmd: cp -rpf build/* ${HOME}/tools/arch/mybins/
